import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <main className=" min-h-screen ">
          <Header />
          {children}
        </main>
       
        <footer className="bg-black p-10 text-white w-full " >
          <p className="text-center py-4 text-sm text-zinc-500">
            &copy; 2024 Raças de Cachorros. Todos os direitos reservados.
            <span>Versão: 1.0.0 </span>
          </p>
        </footer>
      </body>
    </html>
  );
}
